# Generated by Django 2.0.4 on 2018-04-21 19:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logon', models.CharField(max_length=20, unique=True)),
                ('senha', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('celular', models.IntegerField(null=True, unique=True)),
                ('foto', models.CharField(max_length=255, null=True)),
                ('dtExpiracao', models.DateField(default=django.utils.timezone.now)),
                ('ra', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Aberta', 'Aberta'), ('Teste', 'Teste')], max_length=6)),
                ('extra', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='atividadeVinculada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(max_length=100)),
                ('dtInicioRespostas', models.DateField(blank=True, null=True)),
                ('dtFimRespostas', models.DateField(blank=True, null=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='coordenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logon', models.CharField(max_length=20, unique=True)),
                ('senha', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('celular', models.IntegerField(null=True, unique=True)),
                ('dtExpiracao', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now, null=True)),
                ('statusDisc', models.CharField(choices=[('Aberta', 'Aberta'), ('Fechada', 'Fechada')], default='Aberto', max_length=20, null=True)),
                ('planoDeEnsino', models.TextField()),
                ('cargaHoraria', models.IntegerField(choices=[(80, '80 horas'), (40, '40 horas')])),
                ('competencias', models.TextField()),
                ('habilidades', models.TextField()),
                ('ementa', models.TextField()),
                ('conteudoProgramatico', models.TextField()),
                ('bibliografiaBasica', models.TextField()),
                ('bibliografiaComplementar', models.TextField()),
                ('percentualPratico', models.IntegerField()),
                ('percentualTeorico', models.IntegerField()),
                ('idCoordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coordenador')),
            ],
        ),
        migrations.CreateModel(
            name='entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('resposta', models.TextField()),
                ('dtEntrega', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Entregue', 'Entregue'), ('Corrigido', 'Corrigido')], default='Entregue', max_length=10, null=True)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=2)),
                ('dtAvaliacao', models.DateField()),
                ('obs', models.TextField(blank=True, null=True)),
                ('atividadeVinculada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atividadeVinculada')),
                ('idAluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.TextField()),
                ('referencia', models.TextField(blank=True, null=True)),
                ('conteudo', models.TextField()),
                ('status', models.CharField(choices=[('Enviado', 'Enviado'), ('Lido', 'Lido'), ('Respondido', 'Respondido')], default='Enviado', max_length=10)),
                ('dtEnvio', models.DateField(default=django.utils.timezone.now)),
                ('dtResposta', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('resposta', models.TextField(blank=True, null=True)),
                ('idAluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logon', models.CharField(max_length=20, unique=True)),
                ('senha', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('celular', models.IntegerField(null=True, unique=True)),
                ('dtExpiracao', models.DateField(default=django.utils.timezone.now)),
                ('apelido', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mensagem',
            name='idProfessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='idProfessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor'),
        ),
        migrations.AddField(
            model_name='atividadevinculada',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='idProfessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.professor'),
        ),
    ]
