# Generated by Django 2.0.4 on 2018-04-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='senha',
        ),
    ]
