# Generated by Django 2.0.4 on 2018-04-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_aluno_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinaofertada',
            fields=[
                ('iddisciplinaofertada', models.AutoField(db_column='idDisciplinaOfertada', primary_key=True, serialize=False)),
                ('dtiniciomatricula', models.DateField(blank=True, db_column='dtInicioMatricula', null=True)),
                ('dtfimmatricula', models.DateField(blank=True, db_column='dtFimMatricula', null=True)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('turma', models.CharField(blank=True, max_length=6, null=True)),
                ('metodologia', models.CharField(blank=True, max_length=1000, null=True)),
                ('recursos', models.CharField(blank=True, max_length=1000, null=True)),
                ('criterioavaliacao', models.CharField(blank=True, db_column='criterioAvaliacao', max_length=1000, null=True)),
                ('planodeaulas', models.CharField(blank=True, db_column='planoDeAulas', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'disciplinaOfertada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitacaomatricula',
            fields=[
                ('idsolicitacaomatricula', models.AutoField(db_column='idSolicitacaoMatricula', primary_key=True, serialize=False)),
                ('dtsolicitacao', models.DateField(db_column='dtSolicitacao')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'solicitacaoMatricula',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='aluno',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='atividade',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='atividadevinculada',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='coordenador',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='entrega',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'managed': False},
        ),
    ]
