# Generated by Django 2.0.4 on 2018-05-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180429_2318'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aluno',
            table='aluno',
        ),
        migrations.AlterModelTable(
            name='atividade',
            table='atividade',
        ),
        migrations.AlterModelTable(
            name='atividadevinculada',
            table='atividadeVinculada',
        ),
        migrations.AlterModelTable(
            name='coordenador',
            table='coordenador',
        ),
        migrations.AlterModelTable(
            name='curso',
            table='curso',
        ),
        migrations.AlterModelTable(
            name='disciplina',
            table='disciplina',
        ),
        migrations.AlterModelTable(
            name='entrega',
            table='entrega',
        ),
        migrations.AlterModelTable(
            name='mensagem',
            table='mensagem',
        ),
        migrations.AlterModelTable(
            name='professor',
            table='professor',
        ),
    ]
