# Generated by Django 2.0.4 on 2018-05-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('idatividade', models.AutoField(db_column='idAtividade', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.CharField(max_length=1000)),
                ('conteudo', models.CharField(blank=True, max_length=1000, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('extra', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'atividade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Atividadevinculada',
            fields=[
                ('idatividadevinculada', models.AutoField(db_column='idAtividadeVinculada', primary_key=True, serialize=False)),
                ('rotulo', models.CharField(max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('dtiniciorespostas', models.DateField(blank=True, db_column='dtInicioRespostas', null=True)),
                ('dtfimrespostas', models.DateField(blank=True, db_column='dtFimRespostas', null=True)),
            ],
            options={
                'db_table': 'atividadeVinculada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('identrega', models.AutoField(db_column='idEntrega', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=40, null=True)),
                ('resposta', models.CharField(blank=True, max_length=1000, null=True)),
                ('dtentrega', models.DateField(db_column='dtEntrega')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dtavaliacao', models.DateField(db_column='dtAvaliacao')),
                ('obs', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'entrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitacaomatricula',
            fields=[
                ('idsolicitacaomatricula', models.AutoField(db_column='idSolicitacaoMatricula', primary_key=True, serialize=False)),
                ('dtsolicitacao', models.DateField(db_column='dtSolicitacao')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'solicitacaoMatricula',
                'managed': False,
            },
        ),
    ]
