# Generated by Django 2.0.4 on 2018-05-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idcurso', models.AutoField(db_column='idCurso', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('iddisciplina', models.AutoField(db_column='idDisciplina', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('statusdisc', models.CharField(blank=True, db_column='statusDisc', max_length=20, null=True)),
                ('planodeensino', models.CharField(blank=True, db_column='planoDeEnsino', max_length=1000, null=True)),
                ('cargahoraria', models.IntegerField(blank=True, db_column='cargaHoraria', null=True)),
                ('competencias', models.CharField(blank=True, max_length=1000, null=True)),
                ('habilidades', models.CharField(blank=True, max_length=1000, null=True)),
                ('ementa', models.CharField(blank=True, max_length=1000, null=True)),
                ('conteudoprogramatico', models.CharField(blank=True, db_column='conteudoProgramatico', max_length=1000, null=True)),
                ('bibliografiabasica', models.CharField(blank=True, db_column='bibliografiaBasica', max_length=1000, null=True)),
                ('bibliografiacomplementar', models.CharField(blank=True, db_column='bibliografiaComplementar', max_length=1000, null=True)),
                ('percentualpratico', models.IntegerField(blank=True, db_column='percentualPratico', null=True)),
                ('percentualteorico', models.IntegerField(blank=True, db_column='percentualTeorico', null=True)),
            ],
            options={
                'db_table': 'disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplinaofertada',
            fields=[
                ('iddisciplinaofertada', models.AutoField(db_column='idDisciplinaOfertada', primary_key=True, serialize=False)),
                ('dtiniciomatricula', models.DateField(blank=True, db_column='dtInicioMatricula', null=True)),
                ('dtfimmatricula', models.DateField(blank=True, db_column='dtFimMatricula', null=True)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('turma', models.CharField(blank=True, max_length=6, null=True)),
                ('metodologia', models.CharField(blank=True, max_length=1000, null=True)),
                ('recursos', models.CharField(blank=True, max_length=1000, null=True)),
                ('criterioavaliacao', models.CharField(blank=True, db_column='criterioAvaliacao', max_length=1000, null=True)),
                ('planodeaulas', models.CharField(blank=True, db_column='planoDeAulas', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'disciplinaOfertada',
                'managed': False,
            },
        ),
    ]
