# Generated by Django 2.0.4 on 2018-05-01 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={},
        ),
    ]
