# Generated by Django 2.0.4 on 2018-05-04 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_auto_20180501_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={'managed': False},
        ),
    ]
